net:
    in_channels: 20
    depth: 1
    lr: 0.0001
    dropout: False
    skip: False
    batchnorm: True
    is_refine: True
    norm_type: "minmax_constant"

pose_path: "./dataset/exp010/pose_stabled_020.pt"
attr_path: "./dataset/exp010/attr.pt"

data:
    - dataset:
             attr_path: "./dataset/man3/train_attr.pt"
             ldm_path: "./dataset/man3/train_landmarks.npy"
             id_path: "./dataset/man3/id.pt"
             id_landmark_path: "./dataset/man3/id_landmark-chenlong.npy"
             augmentation: True

val:
    attr_path: "./dataset/exp010/val_attr.pt"
    ldm_path: "./dataset/exp010/val_landmarks.npy"
    id_path: "./dataset/exp010/id.pt"
    id_landmark_path: "./dataset/exp010/id_landmark.npy"

optim:
    step: 200
    gamma: 0.5

batchsize: 128
epochs: 600
show_internal: 100
save_internal: 5


