net:
    in_channels: 20
    depth: 2
    lr: 0.0002
    dropout: False
    skip: False
    batchnorm: True
    norm_type: "minmax_constant"

pose_path: "./dataset/exp010/pose_stabled_020.pt"
attr_path: "./dataset/exp010/attr.pt"

data:
    - dataset:
             attr_path: "./dataset/exp010/train_attr.pt"
             ldm_path: "./dataset/exp010/train_landmarks.npy"
             id_path: "./dataset/exp010/id.pt"
             id_landmark_path: "./dataset/exp010/id_landmark.npy"

val:
    attr_path: "./dataset/exp010/val_attr.pt"
    ldm_path: "./dataset/exp010/val_landmarks.npy"
    id_path: "./dataset/exp010/id.pt"
    id_landmark_path: "./dataset/exp010/id_landmark.npy"

optim:
    step: 100
    gamma: 0.5

batchsize: 64
epochs: 400
show_internal: 100
save_internal: 5


