dataset:
        path: "dataset/kanghui_0"
        batch_size: 8

net:
    in_channels: 7
    lr: 0.0002
    step: 50
    gamma: 0.5
    
eval:
    config_path: ./scripts/config.yaml

internal: 100
eval_internal: 5
epochs: 100



