net:
    in_channels: 20
    depth: 2
    lr: 0.0002

data:
    attr_path: "./tests/exp006.pt"
    ldm_path: "./tests/lm2d.npy"
    id_path: "./tests/id.pt"

batchsize: 8
epochs: 20
show_internal: 100
save_internal: 5


