#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/exp010/lm2d.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/tx/ldm_renorm.npy"
#landmarks_path: "/data1/Dataset/chenlong/tx/tx_lm2d.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/landmarks_ADt.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/landmarks_paT.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/landmarks_OPG.npy"
landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/landmarks_xmS.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/shutup.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/transformed.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/landmarks_OKG.npy"

net:
    config: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/scripts/exp065/config.yaml"
    weight: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/results/exp065/snapshots/best.pth"
pti:
    weight: "/data1/chenlong/0517/video/0522/2/results/man3_chenl_0521/man3_pivot_512/snapshots/"

attr_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/man3/attribute-chenlong.pt"
e4e_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/man3/id.pt"
pose_latent_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/TalkingFace/ExpressiveVideoStyleGanEncoding/results/man3/pose"
video_landmark: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/man3/ldm3_chenlong.npy"
driving_images_dir: "/data1/chenlong/0517/video/0522/2/results/man3_chenl_0521/data/smooth"
resolution: 512
frames: -1




