landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/landmarks_byx.npy"
#landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/Yd7ehnqJ/train_landmarks.npy"
net:
    config: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/scripts/exp191/config.yaml"
    weight: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/results/exp191/snapshots/best.pth"

#net:
#    config: "/data1/chenlong/online_model_set/speed/exp_speed_v3/lm_train/scripts/Yd7ehnqJ/config.yaml"
#    weight: "/data1/chenlong/online_model_set/speed/exp_speed_v3/lm_train/results/Yd7ehnqJ/snapshots/best.pth"
pti:
    weight: "/data1/chenlong/online_model_set/speed/exp_speed_v3/exp/Yd7ehnqJ/v3_pti_512_ft5/snapshots"

attr_path: "/data1/chenlong/online_model_set/speed/exp_speed_v3/lm_train/datasets/Yd7ehnqJ/attribute.pt"

e4e_path: "/data1/chenlong/online_model_set/speed/exp_speed_v3/lm_train/datasets/Yd7ehnqJ/id.pt"

pose_latent_path: "/data1/chenlong/online_model_set/speed/exp_speed_v3/exp/Yd7ehnqJ///pose"

video_landmark: "/data1/chenlong/online_model_set/speed/exp_speed_v3/lm_train/datasets/Yd7ehnqJ/lm3d.npy"
id_landmark: "/data1/chenlong/online_model_set/speed/exp_speed_v3/lm_train/datasets/Yd7ehnqJ/id_landmark.npy"

#driving_images_dir: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/TalkingFace/ExpressiveVideoStyleGanEncoding/results/outoutP/smooth"
driving_images_dir: "/data1/chenlong/online_model_set/face/Yd7ehnqJ/face"

resolution: 512
frames: -1
