landmarks_path: "/data1/chenlong/local_code/StyleExpressiveTalkingFace-master/tx_lm2d.npy"

net:
    config: "/data1/chenlong/online_model_set/lm_train_data/scripts/Yd7ehnqJ/config.yaml"
    weight: "/data1/chenlong/online_model_set/lm_train_data/results/Yd7ehnqJ/snapshots/best.pth"

pti:
    weight: "/data1/chenlong/online_model_set/exp_ori/Yd7ehnqJ/results/pti_ft_512/snapshots"

attr_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/attribute.pt"

e4e_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/id.pt"

pose_latent_path: "/data1/chenlong/online_model_set/exp_ori/Yd7ehnqJ/results/pose"

video_landmark: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/lm3d.npy"
id_landmark: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/id_landmark.npy"

driving_images_dir: "/data1/chenlong/online_model_set/face/Yd7ehnqJ/face"

resolution: 512
frames: 200