landmarks_path: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/dataset/landmarks_Mzfv2.npy"

net:
    config: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/lm_train/scripts/iJK2T0kN_exp_set_v4_depoly/config.yaml"
    weight: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/lm_train/results/iJK2T0kN_exp_set_v4_depoly/snapshots/best.pth"

pti:
    weight: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/exp/pti_ft_512/snapshots"

attr_path: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/lm_train/datasets/iJK2T0kN_exp_set_v4_depoly/attribute.pt"

e4e_path: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/lm_train/datasets/iJK2T0kN_exp_set_v4_depoly/id.pt"

pose_latent_path: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/exp/pose"

video_landmark: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/lm_train/datasets/iJK2T0kN_exp_set_v4_depoly/lm3d.npy"
id_landmark: "/data1/chenlong/0517/video/0822/iJK2T0kN/iJK2T0kN_exp_set_v4_depoly/lm_train/datasets/iJK2T0kN_exp_set_v4_depoly/id_landmark.npy"

driving_images_dir: "/data1/wanghaoran/Amemori/StyleExpressiveTalkingFace/TalkingFace/ExpressiveVideoStyleGanEncoding/results/output/smooth"
video_images_path: "/data1/chenlong/online_model_set/video/iJK2T0kN/video/smooth"

resolution: 512
frames: -1
