net:
    in_channels: 20
    depth: 1
    lr: 0.0002

pose_path: "./dataset/exp010/pose_stabled_004.pt"
id_path: "./dataset/exp010/id.pt"
data:
    - train_1:
             attr_path: "./dataset/exp010/train_attr.pt"
             ldm_path: "./dataset/exp010/train_landmarks.npy"
             id_landmark_path: "./dataset/exp010/id_landmark.npy"

    - train_2:
             attr_path: "./dataset/exp010/1/attr.pt"
             ldm_path: "./dataset/exp010/1/lm2d_e4e.npy"
             id_landmark_path: "./dataset/exp010/1/id_landmark.npy"

val:
    attr_path: "./dataset/exp010/val_attr.pt"
    ldm_path: "./dataset/exp010/val_landmarks.npy"

optim:
    step: 10
    gamma: 0.5

batchsize: 8
epochs: 40
show_internal: 100
save_internal: 5

