net:
    in_channels: 20
    depth: 1
    lr: 0.0002

data:
    attr_path: "./dataset/exp010/attr.pt"
    ldm_path: "./dataset/exp010/lm2d_e4e.npy"
    id_path: "./dataset/exp010/id.pt"
    ratio: 0.9

optim:
    step: 10
    gamma: 0.5

batchsize: 8
epochs: 40
show_internal: 100
save_internal: 5

