net:
    in_channels: 25
    depth: 1
    lr: 0.0002
    dropout: False
    skip: False
    batchnorm: True
    is_refine: True
    norm_type: "minmax_constant"
    norm_dim: [ 0 ]


pose_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/pose.pt"
attr_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/attribute.pt"

data:
    - dataset:
             attr_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/train_attr.pt"
             ldm_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/train_landmarks.npy"
             id_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/id.pt"
             id_landmark_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/id_landmark.npy"
             augmentation: True

val:
    attr_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/val_attr.pt"
    ldm_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/val_landmarks.npy"
    id_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/id.pt"
    id_landmark_path: "/data1/chenlong/online_model_set/lm_train_data/datasets/Yd7ehnqJ/id_landmark.npy"

optim:
    step: 150
    gamma: 0.5

batchsize: 128
epochs: 450
show_internal: 100
save_internal: 5


